# Generated by Django 3.1.2 on 2020-10-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Seller ID')),
                ('type', models.CharField(choices=[('CORPORATE', 'Corporate'), ('INDIVIDUAL', 'Individual')], max_length=20, verbose_name='Seller Type')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('date', models.IntegerField(verbose_name='Date')),
                ('expiryDate', models.IntegerField(verbose_name='Expiry Date')),
                ('live', models.BooleanField(default=False, verbose_name='Live')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WAITING_APPROVAL', 'Waiting Approval'), ('PASSIVATED', 'Passivated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], max_length=20, verbose_name='Status')),
                ('adminID', models.IntegerField(default=0, verbose_name='Admin ID')),
                ('categories', models.ManyToManyField(blank=True, default=None, to='API.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to='API.seller', verbose_name='Seller')),
            ],
        ),
    ]
