# Generated by Django 3.1.2 on 2020-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20201016_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='adminID',
            field=models.BigIntegerField(default=0, verbose_name='Admin ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.BigIntegerField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiryDate',
            field=models.BigIntegerField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='Price'),
        ),
    ]
